#!/usr/bin/env bash
# shellcheck shell=bash
set -euf -o pipefail

# Copy files from the scaffold to the project.
mkdir -p ./assets/scripts
rsync -a vendor/cherryhill/isle-st-composer-scaffold/scaffold/scripts .
