#!/usr/bin/env bash
# shellcheck shell=bash
set -e -o pipefail

# Merge the scaffold configuration into the project’s composer.json
curl -LsSf https://raw.githubusercontent.com/cherryhill/edit-composer-json/2.x/merge | bash -s -f drupal/rootfs/var/www/drupal/composer.json cherryhill/isle-st-composer-scaffold@2.x

# Create scripts directory
mkdir -p drupal/rootfs/var/www/drupal/assets/scripts

# Create symbolic link
ln -s drupal/rootfs/var/www/drupal/assets/scripts scripts
