#!/usr/bin/env bash
# shellcheck shell=bash
set -euf -o pipefail

# Copy files from the scaffold repository to the Drupal assets directory.
cp -a ./vendor/cherryhill/isle-st-composer-scaffold/scaffold/scripts ./assets
